-- MySQL Script generated by MySQL Workbench
-- Mon Dec 15 02:03:05 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`user` ;

CREATE TABLE IF NOT EXISTS `mydb`.`user` (
  `iduser` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `rol` ENUM('STUDENT', 'TEACHER', 'ADMINISTRATIVE_STAFF') NOT NULL,
  PRIMARY KEY (`iduser`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`type_of_procedure`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`type_of_procedure` ;

CREATE TABLE IF NOT EXISTS `mydb`.`type_of_procedure` (
  `idtype_of_procedure` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idtype_of_procedure`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`document_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`document_type` ;

CREATE TABLE IF NOT EXISTS `mydb`.`document_type` (
  `iddocument_type` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`iddocument_type`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`proceduretypedocumentrequirement`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`proceduretypedocumentrequirement` ;

CREATE TABLE IF NOT EXISTS `mydb`.`proceduretypedocumentrequirement` (
  `type_of_procedure_idtype_of_procedure` INT NOT NULL,
  `document_type_iddocument_type` INT NOT NULL,
  PRIMARY KEY (`type_of_procedure_idtype_of_procedure`, `document_type_iddocument_type`),
  CONSTRAINT `fk_type_of_procedure_has_document_type_type_of_procedure`
    FOREIGN KEY (`type_of_procedure_idtype_of_procedure`)
    REFERENCES `mydb`.`type_of_procedure` (`idtype_of_procedure`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_type_of_procedure_has_document_type_document_type1`
    FOREIGN KEY (`document_type_iddocument_type`)
    REFERENCES `mydb`.`document_type` (`iddocument_type`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_type_of_procedure_has_document_type_document_type1_idx` ON `mydb`.`proceduretypedocumentrequirement` (`document_type_iddocument_type` ASC) VISIBLE;

CREATE INDEX `fk_type_of_procedure_has_document_type_type_of_procedure_idx` ON `mydb`.`proceduretypedocumentrequirement` (`type_of_procedure_idtype_of_procedure` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`through`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`through` ;

CREATE TABLE IF NOT EXISTS `mydb`.`through` (
  `idthrough` INT NOT NULL AUTO_INCREMENT,
  `iduser` INT NOT NULL,
  `idtype_of_procedure` INT NOT NULL,
  `description` TEXT NOT NULL,
  `iduserservant` INT NULL,
  `state` ENUM('FILED', 'IN_PROCESS', 'FINALIZED', 'REJECTED') NOT NULL,
  `creationdate` DATE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`idthrough`),
  CONSTRAINT `fk_through_user1`
    FOREIGN KEY (`iduser`)
    REFERENCES `mydb`.`user` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_through_type_of_procedure1`
    FOREIGN KEY (`idtype_of_procedure`)
    REFERENCES `mydb`.`type_of_procedure` (`idtype_of_procedure`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_through_user2`
    FOREIGN KEY (`iduserservant`)
    REFERENCES `mydb`.`user` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_through_user1_idx` ON `mydb`.`through` (`iduser` ASC) VISIBLE;

CREATE INDEX `fk_through_type_of_procedure1_idx` ON `mydb`.`through` (`idtype_of_procedure` ASC) VISIBLE;

CREATE INDEX `fk_through_user2_idx` ON `mydb`.`through` (`iduserservant` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`attachment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`attachment` ;

CREATE TABLE IF NOT EXISTS `mydb`.`attachment` (
  `idattachment` INT NOT NULL AUTO_INCREMENT,
  `idthrough` INT NOT NULL,
  `url` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idattachment`),
  CONSTRAINT `fk_attachment_through1`
    FOREIGN KEY (`idthrough`)
    REFERENCES `mydb`.`through` (`idthrough`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_attachment_through1_idx` ON `mydb`.`attachment` (`idthrough` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`tracing`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`tracing` ;

CREATE TABLE IF NOT EXISTS `mydb`.`tracing` (
  `idtracing` INT NOT NULL AUTO_INCREMENT,
  `through_idthrough` INT NOT NULL,
  `user_iduser` INT NOT NULL,
  `comment` TEXT NOT NULL,
  `creationdate` DATE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`idtracing`),
  CONSTRAINT `fk_tracing_through1`
    FOREIGN KEY (`through_idthrough`)
    REFERENCES `mydb`.`through` (`idthrough`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tracing_user1`
    FOREIGN KEY (`user_iduser`)
    REFERENCES `mydb`.`user` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_tracing_through1_idx` ON `mydb`.`tracing` (`through_idthrough` ASC) VISIBLE;

CREATE INDEX `fk_tracing_user1_idx` ON `mydb`.`tracing` (`user_iduser` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
